
#主监听
Listen = ":8342"

#DB数据库
#DBType = "postgres"
#DBHost = "postgres://postgres:postgres@10.5.50.161/s999_slg?sslmode=disable"
DBType = "mysql"
#生产环境
DBHost = "root:1614@tcp(localhost:3306)/slg_sample?charset=utf8"
#本地开发
DBHostDev = "root:1614@tcp(localhost:3306)/slg_sample?charset=utf8"

#Redis
